name: CD - Deploy Frontend to S3

on:
  push:
    branches:
      - main
    paths:
      - "index.html"
      - "*.html"
      - "*.js"
      - "*.css"
      - "assets/**"
      - ".github/workflows/frontend_deploy.yml"
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    # Needed for OIDC â†’ AWS role assumption
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Sync static frontend to S3
        run: |
          echo "Deploying to bucket: sot4-model-registry-dev"
          aws s3 sync . s3://sot4-model-registry-dev/ \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "backend/*" \
            --exclude "src/*" \
            --exclude "tests/*" \
            --exclude "*.py" \
            --exclude "requirements.txt" \
            --exclude "README.md" \
            --delete